In [8]:
import numpy as np
import random as rnd

utfall = np.zeros(6)
antal_kast = 100000

print(utfall)
utfall[2] = 20

for i in range(antal_kast):
    kast = rnd.randint(1,6)
    utfall[kast-1] += 1

print(f"tärningskast{utfall}")
print(f"sannolikhet{utfall/antal_kast}")

[0. 0. 0. 0. 0. 0.]
[16704. 16653. 16702. 16666. 16651. 16644.]
[0.16704 0.16653 0.16702 0.16666 0.16651 0.16644]
